apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: pipe
        image: gcr.io/nice-gate-272207/pipe:v1
        ports:
        - containerPort: 80
