apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-deployment
spec:
  selector:
    matchLabels:
      app: bonsai-landing
  replicas: 1
  template:
    metadata:
      labels:
        app: vino
    spec:
     containers:
     - name: sample-app
       image: gcr.io/nice-gate-272207/test
       ports:
       - containerPort: 8080
