apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-deployment
  labels:
    name: sample-app-deployment
    app: vino
spec:
  containers:
  - name: sample-app
    image: gcr.io/nice-gate-272207/test
    ports:
         - containerPort: 80
