apiVersion: v1
kind: Service
metadata:
  name: sample-service
  labels:
    name: sample-service
    app: web
spec:
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  selector:
     name: sample-app
     app: web
