apiVersion: apps/v1
kind: Service
metadata:
  name: sample-service
  labels:
    name: sample-service
    app: vino
spec:
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  selector:
     name: sample-app-deployment
     app: vino
